-- Obsolete — do NOT run this file.
-- Replaced by migration_15_coa_sub_heads.sql (Buyer / Seller / Misc Parties are now
-- real, editable Sub Heads in Chart of Accounts). If you already ran this file, nothing
-- breaks: its party_type column is simply no longer used. Safe to delete.
