-- Obsolete — do NOT run this file.
-- It was replaced by migration_11_ibft_voucher.sql (IBFT is now stored
-- through voucher_lines, so the extra column this file added isn't needed).
-- Safe to delete.
